---
Project title: "Data Science with R Project Proposal"
output:
  rmarkdown::html_document:
    theme: lumen
bibliography: bibliography.bib 
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
``` 

### Project Proposal on Customer Behavioural Analytics in the Retail sector 
<br> 
__Project title:__ <font color ="black"> "Customer Behavioural Analytics in the Retail sector" <br /> </font> </font>

__Names of team members:__<br /> 
<font color ="black">
1. Nadiia Honcharenko (220681, nadiia.honcharenko@st.ovgu.de) <br />
2. Rutuja Shivraj Pawar (220051, rutuja.pawar@ovgu.de) <br />
3. Shivani Jadhav () <br />
4. Sumit Kundu () 
</font>

__Under the Guidance of:__ <font color ="black"> M.Sc. Uli Niemann </font>

__Date:__ <font color ="black"> ```r format(Sys.Date(), "%B %e, %Y")``` </font>

__Background and motivation:__ <font color ="black"> 
<p>Consumer behavior is the series of behaviors or patterns that consumers follow before making a purchase.
Understanding, analyzing and keeping track of customer decisions 
helps to increase an annual revenue of companies and satisfy the needs of clients.</p>
<p>In this project we are trying to research a customer behaviour during shopping, 
how consumers make buying decisions and what influences those decisions.
This study shows that products have a "range" effect:
for some products, customers travel long distances, while
for other products they settle down with the closest shop. 
We want to check the existence of dependencies between product prices, 
their uniqueness and location of a store, then compare and explain them. </p>
 </font>

__Project objectives:__ <font color ="black"> 
<ul>
<li>Find and investigate the dependencies between product prices, 
their uniqueness and distance to a shop</li>
<li>Show when customers overcome long distances to stores</li>
<li>Predict a customer behaviour to 
improve marketing strategy of the shop</li>
</ul>
</font>

__Name of the dataset to be used:__ <font color ="black"> Supermarket aggr.Customer^[https://bigml.com/user/czuriaga/gallery/dataset/5559c2c6200d5a6570000084] <br />
The dataset to be used is the retail market data of one of the largest Italian retail distribution company called _Coop_ for a single Italian city [@pennacchioli2013explaining].<br />
The Supermarket aggr.Customer dataset used for the analysis contains data aggregated from the original datasets^[http://www.michelecoscia.com/?page_id=379] [@pennacchioli2013explaining] and mapped to new columns. The dataset thus contains 40 features with 60,366 instances and is approximately 14.0 MB in size. </font> 


__Design overview:__ <font color ="black"> </font>

__Time plan:__ <font color ="black"> </font>

__GitHub Repository:__ https://github.com/Rspawar/Data-Science-with-R.git 

__References:__



---
#Comments

# Dont display warnings
# {r, warning = FALSE}

# Dont display code
# {r, echo=FALSE}

# To store long computation results in a local cache
# {r, cache=TRUE}

# Exmaple usage of labelling and reusing code chunks
# ```{r iris_plot, echo = FALSE, eval = FALSE}
# library(ggplot2)
# ggplot(iris, aes(x = Species, y = Sepal.Length)) + geom_boxplot()
#```

# ```{r , ref.label='iris_plot', fig.width = 7, fig.height = 2.5}
# ```

# Inline R code usng r
# A random sample of 5 numbers from the set of numbers between 
# 1 and 10 is `r sample(1:10, 5)` 
---